version: '3.8'
services:
  app:
    build: .
    command: bash -c "yarn start"
    container_name: yale_college_hub
    depends_on:
      - db
    env_file:
      - .env.local
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated

  db:
    image: postgres
    container_name: yale-college-hub-db
    env_file:
      - .env.local
    volumes:
      - .:/app
      - dbvolume:/var/lib/postgresql/data

volumes:
  dbvolume:
