version: '3.8'
services:
  backend: # This container runs the backend, which contains all the endpoints and enables the API
    build: . # build the image for the backend container according to ./Dockerfile
    container_name: yalebutteries
    depends_on:
      - db # make sure the database is running before this runs
    env_file:
      - .env.local # use secret environment variables in .env.local
    ports:
      - '3000:3000' # Open port 3000 to the outside world
    volumes:
      - ./prisma/:/app/prisma/ # when the container makes a new prisma migration, your local code is updated to match
      - ./src:/app/src # when the code is changed in your local environment, it automatically changes in the container so you don't need to rebuild it
    command: bash -c "yarn start"

  db: # This container holds the database, which the backend interacts with
    image: postgres
    container_name: yalebutteries-db
    env_file:
      - .env.local
    volumes:
      - dbvolume:/var/lib/postgresql/data` # The database is stored on a volume so that the data persists even after the container shuts down

volumes:
  dbvolume:
